### ISSUE TITLE
some problem about  undefined symbol:_ZNK10tensorflow8OpKernel11TraceStringERKNS_15OpKernelContextEb 

### ISSUE THREAD

**Issue by jzl20** [kimbring2/MOBA_RL#2]
when I run the      
  python learner_1.py --workspace_path [your path]/dr-derks-mutant-battlegrounds/

I meet some problems like this :

tensorflow.python.framework.errors_impl.NotFoundError: /home/public/grpc/python/../grpc_cc.so: undefined symbol: _ZNK10tensorflow8OpKernel11TraceStringERKNS_15OpKernelContextEb

**Comment by kimbring2** [comment]
@jzl20 Hello, I know that problem. It happens when the GRPC version is not compatible with the Tensorflow version.  

I entirely borrow the training code from https://github.com/google-research/seed_rl. You can check the folder from there named https://github.com/google-research/seed_rl/tree/master/grpc.

In my experience, we should use the Tensorflow 2.4.1 version for that. 

Try to change the version and tell the result.

Thank you

**Comment by jzl20** [comment]
@kimbring2  
GREAT !!!    It works !
Thank you very much !

If possible , I wish you can modify  the 'requirements.txt' [https://github.com/kimbring2/MOBA_RL/blob/main/dr-derks-mutant-battlegrounds/requirements.txt](url) . (tensorflow-cpu==2.2.0 . It dose not work )
 
-----------------------------------
At the same time , I want to share some other Error code to help others 
tensorflow 2.2.0  meets undefined symbol:  _ZNK10tensorflow8OpKernel11TraceStringERKNS_15OpKernelContextEb
tensorflow 2.6.0  meets undefined symbol:  _ZN4absl14lts_2020_02_2518container_internal18global_next_sampleE
And other Error code about the Tensorflow version:  ImportError: cannot import name 'dtensor' from 'tensorflow.compat.v2.experimental'
-----------------------------------
What a lucky day with the help of the author！

**Comment by kimbring2** [comment]
@jzl20 I am happy your code is now working well. Also, thank you for your advice. 

Feel free to ask another question when you are stuck +1:

**Comment by jzl20** [comment]
hahaha , so friendly you are . ^_^
